name: CI - Pytest & Pylint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install pylint pytest aiohttp homeassistant pyyaml
        # Aktualisiert pip und installiert pylint sowie Abhängigkeiten für Home Assistant-Adapter

      # 4. Pylint ausführen
      - name: Analysing the code with pylint
          pip install --upgrade setuptools wheel
          pip install pylint pytest aiohttp homeassistant pyyaml

      - name: Check installed packages
        run: |
          pip freeze

      - name: Run pylint
        run: |
          pylint $(git ls-files '*.py')
