name: Pylint Check

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      # 1. Repository auschecken
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Python-Umgebung einrichten
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Systemabhängige Abhängigkeiten installieren (z.B. build-essential, libyaml-dev)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libyaml-dev

      # 4. Caching von Python-Abhängigkeiten
      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 5. Abhängigkeiten installieren
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install pylint pytest aiohttp homeassistant pyyaml --prefer-binary

      # 6. Pylint ausführen
      - name: Run pylint
        run: |
          pylint $(git ls-files '*.py')
