# Name des Workflows, der in GitHub Actions angezeigt wird
name: Pylint Check

# Der Workflow wird bei jedem Push aufgerufen
on: [push]

# Definition des Jobs, der den Code analysiert
jobs:
  pylint:
    # Der Job wird auf der neuesten Ubuntu-Umgebung ausgeführt
    runs-on: ubuntu-latest

    # Der Job wird für mehrere Python-Versionen ausgeführt
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      # 1. Repository auschecken
      - name: Checkout Repository
        uses: actions/checkout@v4
        # Lädt den aktuellen Code aus dem Repository in die Arbeitsumgebung

      # 2. Python-Umgebung einrichten
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
        # Richtet die Python-Version ein, die in der Matrix angegeben ist

      # 3. Abhängigkeiten installieren
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint aiohttp homeassistant
        # Aktualisiert pip und installiert pylint sowie Abhängigkeiten für Home Assistant-Adapter

      # 4. Pylint ausführen
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
        # Führt pylint für alle Python-Dateien im Repository aus
