name: Run Pytest for Schulferien Integration

on: [push]

jobs:
  test:
    name: Run Tests with Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt

      # Führe die Tests mit pytest aus
      - name: Run tests
        run: |
          pytest tests --cov=custom_components/schulferien --cov-report=xml
