name: Run Pytest for Schulferien Integration

on: [push]

jobs:
  test:
    name: Run Tests with Pytest
    runs-on: ubuntu-latest

    # Hinweis: Node.js 24 wird ab 2. Juni 2026 standardmäßig verwendet.
    # Node.js 20 wird am 16. September 2026 vom Runner entfernt.
    # Siehe: https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt

      # Führe die Tests mit pytest aus
      - name: Run tests
        run: |
          pytest tests --cov=custom_components/schulferien --cov-report=xml
